[project]
name = "dataquality"
version = "0.1.0"
description = "Example"
requires-python = ">=3.12"
dependencies = [
    "pydeequ>=1.4.0",
    "pyspark>=3.5.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["."]
