{
 "title": "C* Cluster Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "rate",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cluster",
    "query": "label_values(up{job=\"cassandra\"}, cluster)"
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=\"cassandra\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total Storage Size",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 2, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (cluster) (cassandra_keyspace_livediskspaceused{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Avg per Node",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (cluster) (cassandra_keyspace_livediskspaceused{cluster=\"$cluster\"}) / scalar(count(up{job=\"cassandra\", cluster=\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 1 },
   "format": "wps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (cluster) (irate(cassandra_clientrequest_latency{cluster=\"$cluster\",clientrequest=\"Write\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 1 },
   "format": "rps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (cluster) (irate(cassandra_clientrequest_latency{cluster=\"$cluster\",clientrequest=\"Read\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Avg Write Latency",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 1 },
   "format": "µs",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (cluster) (irate(cassandra_clientrequest_totallatency{cluster=\"$cluster\",clientrequest=\"Write\"}[$rate])) / sum by (cluster) (irate(cassandra_clientrequest_latency{cluster=\"$cluster\",clientrequest=\"Write\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Avg Read Latency",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 1 },
   "format": "µs",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (cluster) (irate(cassandra_clientrequest_totallatency{cluster=\"$cluster\",clientrequest=\"Read\"}[$rate])) / sum by (cluster) (irate(cassandra_clientrequest_latency{cluster=\"$cluster\",clientrequest=\"Read\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Blocked Tasks",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (cluster) (sum_over_time(cassandra_threadpools_currentlyblockedtasks{cluster=\"$cluster\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Dropped Messages",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (cluster) (increase(cassandra_droppedmessage_dropped{cluster=\"$cluster\"}[$rate]))"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{cluster=\"$cluster\",mode=\"idle\"}[$rate])) * 100)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_network_receive_bytes_total{cluster=\"$cluster\",device!=\"lo\"}[$rate]) + irate(node_network_transmit_bytes_total{cluster=\"$cluster\",device!=\"lo\"}[$rate]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Avg Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_written_bytes_total{cluster=\"$cluster\"}[$rate]) + irate(node_disk_read_bytes_total{cluster=\"$cluster\"}[$rate]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{cluster=\"$cluster\",area=\"heap\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Read/Write Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster) (irate(cassandra_clientrequest_latency{cluster=\"$cluster\",clientrequest=\"Write\"}[$rate])) / (sum by (cluster) (irate(cassandra_clientrequest_latency{cluster=\"$cluster\",clientrequest=\"Write\"}[$rate])) + (sum by (cluster) (irate(cassandra_clientrequest_latency{cluster=\"$cluster\",clientrequest=\"Read\"}[$rate])))) ",
     "legendFormat": "Writes"
    },
    {
     "expr": "sum by (cluster) (irate(cassandra_clientrequest_latency{cluster=\"$cluster\",clientrequest=\"Read\"}[$rate])) / (sum by (cluster) (irate(cassandra_clientrequest_latency{cluster=\"$cluster\",clientrequest=\"Write\"}[$rate])) + (sum by (cluster) (irate(cassandra_clientrequest_latency{cluster=\"$cluster\",clientrequest=\"Read\"}[$rate])))) ",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 15 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(cassandra_clientrequest_latency{cluster=\"$cluster\",clientrequest=\"Write\"}[$rate]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Write Avg Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 15 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(cassandra_clientrequest_totallatency{cluster=\"$cluster\",clientrequest=\"Write\"}[$rate])) / sum by (instance) (irate(cassandra_clientrequest_latency{cluster=\"$cluster\",clientrequest=\"Write\"}[$rate]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 15 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(cassandra_clientrequest_latency{cluster=\"$cluster\",clientrequest=\"Read\"}[$rate]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Read Avg Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 15 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(cassandra_clientrequest_totallatency{cluster=\"$cluster\",clientrequest=\"Read\"}[$rate])) / sum by (instance) (irate(cassandra_clientrequest_latency{cluster=\"$cluster\",clientrequest=\"Read\"}[$rate]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}