{
 "title": "System Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "rate",
    "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instance",
    "query": "label_values(up{job=\"node\"}, instance)"
   },
   { "name": "jobname", "label": "Job name of node exporter", "query": "${VAR_JOBNAME}" },
   { "name": "device_filter_regex", "query": "${VAR_DEVICE_FILTER_REGEX}" }
  ]
 },
 "panels": [
  { "title": "CPU $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum by (mode) (rate(node_cpu_seconds_total{instance=~\"$instance\"}[$rate])) * 100) / scalar(count(node_cpu_seconds_total{mode=\"user\", instance=~\"$instance\"}))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "CPU % By Core",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{instance=~\".*$instance.*\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{ cpu }}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance\"}",
     "legendFormat": "1"
    },
    {
     "expr": "node_load5{instance=~\"$instance\"}",
     "legendFormat": "5"
    },
    {
     "expr": "node_load15{instance=~\"$instance\"}",
     "legendFormat": "15"
    }
   ]
  },
  { "title": "Disks - $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "instance" },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$instance\",device!~'$device_filter_regex'}[$rate])",
     "legendFormat": "{{ device }} reads"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$instance\",device!~'$device_filter_regex'}[$rate])",
     "legendFormat": "{{ device }} writes"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$instance\",device!~'$device_filter_regex'}[$rate]) + irate(node_disk_writes_completed_total{instance=~\"$instance\",device!~'$device_filter_regex'}[$rate])",
     "legendFormat": "{{ device }} total"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$instance\",device!~\"$device_filter_regex\"}[$rate]) * 100",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$instance\",device!~\"$device_filter_regex\"}[$rate])",
     "legendFormat": "{{ device }} write"
    }
   ]
  },
  {
   "title": "Read",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$instance\",device!~\"$device_filter_regex\"}[$rate])",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(irate(node_disk_read_time_seconds_total{instance=~\"$instance\",device!~\"$device_filter_regex\"}[$rate]) / irate(node_disk_reads_completed_total{instance=~\"$instance\",device!~\"$device_filter_regex\"}[$rate]))",
     "legendFormat": "{{ device }} read"
    },
    {
     "expr": "(irate(node_disk_write_time_seconds_total{instance=~\"$instance\",device!~\"$device_filter_regex\"}[$rate]) / irate(node_disk_writes_completed_total{instance=~\"$instance\",device!~\"$device_filter_regex\"}[$rate]))",
     "legendFormat": "{{ device }} write"
    }
   ]
  },
  {
   "title": "Free space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (mountpoint) (node_filesystem_free_bytes{instance=~\"$instance\",device!~\"$device_filter_regex\"} / node_filesystem_size_bytes{instance=~\"$instance\",device!~\"$device_filter_regex\"} * 100)",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  { "title": "Misc - $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "instance" },
  {
   "title": "Network Rate - $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$instance\",device!=\"lo\"}[$rate]) * -1",
     "legendFormat": "{{ device }} TX"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$instance\",device!=\"lo\"}[$rate])",
     "legendFormat": "{{ device }} RX"
    }
   ]
  },
  {
   "title": "Memory Distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"} - (node_memory_MemFree_bytes{instance=~\"$instance\"} + node_memory_Buffers_bytes{instance=~\"$instance\"} + node_memory_Cached_bytes{instance=~\"$instance\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$instance\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$instance\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "\nnode_memory_Cached_bytes{instance=~\"$instance\"}",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$instance\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "node_filefd_maximum{instance=~\"$instance\"}",
     "legendFormat": "Maximum"
    }
   ]
  },
  {
   "title": "Net Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$instance'}",
     "legendFormat": "Established"
    }
   ]
  }
 ]
}