# Simple postgres server for using with self-deployment airflow for learning
# it can be used when configuring airflow with Celery executor
version: '3.5'
services:
  airflowdb:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=cse4640
      - POSTGRES_PASSWORD=cse4640test
      - POSTGRES_DB=airflowdb
      - PGDATA=/var/lib/postgresql/data/pgdata
    # update according to your configuration
    volumes:
      - /opt/data/postgres:/var/lib/postgresql/data
